WIP: Speed up by caching translation values in class variables (in memory)
prograils/lit pull request #158
Opened 2021-01-29 21:51 UTC by mlitwiniuk

Just a crazy experiment to cache translation values in memory by using class variables...

2021-01-29 21:52 UTC, mlitwiniuk commented on lib/lit/adapters/redis_storage.rb
> +      ::Rails.logger.info('terefere')
to be removed, helps to spot call to `exists?` easily in console ;)

2021-02-01 10:58 UTC, pnikrat requested changes

2021-02-01 15:14 UTC, pnikrat requested changes
Looks ok to me. Just one line needs removal, that's all

2021-02-01 15:14 UTC, pnikrat commented on app/controllers/lit/localizations_controller.rb
> +      Lit.get_key_value_engine['lit_last_updated_at'] = Time.now.to_i
You no longer need this value after changes in cache.rb file. Now you just check DB for latest updated_at. I think it should be removed for clarity

2021-03-04 14:59 UTC, merged